### ISSUE TITLE
KeyError('ckanext') in site.py while processing ckanext_datarequests-0.2.13-py2.7-nspkg.pth

### ISSUE THREAD

**Issue by scardine** [conwetlab/ckanext-datarequests#20]
Out of the blue, I started getting this exception:

    Traceback (most recent call last):
      File "/usr/lib/ckan/default/lib/python2.7/site.py", line 702, in <module>
        main()
      File "/usr/lib/ckan/default/lib/python2.7/site.py", line 682, in main
        paths_in_sys = addsitepackages(paths_in_sys)
      File "/usr/lib/ckan/default/lib/python2.7/site.py", line 281, in addsitepackages
        addsitedir(sitedir, known_paths)
      File "/usr/lib/ckan/default/lib/python2.7/site.py", line 203, in addsitedir
        addpackage(sitedir, name, known_paths)
      File "/usr/lib/ckan/default/lib/python2.7/site.py", line 172, in addpackage
        exec(line)
      File "<string>", line 1, in <module>
    KeyError: 'ckanext'

Tried to debug, the KeyError is from `exec(line)` where `line` is any line from '.../site-packages/ckanext_datarequests-0.2.13-py2.7-nspkg.pth'.

I don't know how to further investigate this, if I place a `set_trace()` in a try block around the problematic statement and exec it manually in the debugger, everything works.

**Comment by aitormagan** [comment]
* Are you getting this error at the time of installing the plugin?
* Have you installed the plugin before?
* Which version of CKAN are you using?

**Comment by aitormagan** [comment]
Closed for inactivity.
